### ISSUE TITLE
otree-core, oTree and virtualenv

### ISSUE THREAD

**Issue by pank** [oTree-org/otree-docs#1]
Hi,

As `python3` is the default in my distro, I want to install oTree via `virtualenv`.  But I don't understand  the relationship between the `otree-core` repo and `oTree` repo.  When following the plain instructions I'm instructed to both install the `otree-core` (via `pip`) *and* clone `oTree`.  E.g. `otree` binary of oTree repo seems to be necessary starting oTree.

As such, I would like clearer instructions in the **Plain install** part on how to setup with `virtualenv`.

Thanks,

**Comment by oTree-org** [comment]
Hi, the way you described it is correct. `oTree` is the repo to clone, and `otree-core` is a dependency for `oTree` to work.

To install into a virtualenv, you can follow the same instructions (I always use virtualenv myself). Clone the `oTree` repo, activate the virtualenv, `pip install -r requirements_base.txt`, and then run `python2 otree resetdb`.

Does that work for you?

I will update the docs to clarify.

By the way, we are working on Python3 support: https://github.com/oTree-org/otree-core/issues/296

**Comment by pank** [comment]
oTree-org <notifications@github.com> writes:

> Hi, the way you described it is correct. `oTree` is the repo to clone,
> and `otree-core` is a dependency for `oTree` to work.

I understand it that far, but are the server part of oTree or otree-core.


> To install into a virtualenv, you can follow the same instructions (I
> always use virtualenv myself). Clone the `oTree` repo, activate the
> virtualenv, `pip install -r requirements_base.txt`, and then run
> `python2 otree resetdb`.

I created a new `virtualenv` with `virtualenv2`.  Then I ran `pip2 install
-r requirements_base.txt`.  Then I cloned oTree.  So my root is now
contains two folders, `env` and `oTree`.  I guess that I will then develop
my project in a separate folder, `project` that I add as a supermodel to
`oTree`.

I'm completely new to Django...

> By the way, we are working on Python3 support:
> https://github.com/oTree-org/otree-core/issues/296

Cool.  I prefer `p3` for arbitrary reasons.

Thanks,
Rasmus

-- 
This space is left intentionally blank

**Comment by oTree-org** [comment]
The `oTree` repo itself does not contain the server code; that is in `otree-core` and `Django`, which are both installed as dependencies.

The `oTree` repo is a Django project, as described here:

https://docs.djangoproject.com/en/1.8/intro/tutorial01/#creating-a-project

You should create your apps inside the `oTree` directory you cloned.

In theory, you could create your own Django project from scratch and just import otree-core, but oTree comes pre-configured with all the settings and dependencies so that it works right away. You can delete existing example games if you wish (like `asset_market`, `bargaining`, etc).

**Comment by oTree-org** [comment]
Added to docs: http://otree.readthedocs.org/en/latest/setup.html#explanation-otree-django
